USE [BD_OCEF_CtasPorCobrar]
GO


/*------------------------------------------ Correos ---------------------------------------------------*/


INSERT INTO [dbo].[TS_CorreoAplicacion](T_DireccionCorreo, T_PasswordCorreo, T_Seguridad, T_HostName, I_Puerto, D_FecUpdate, B_Habilitado, B_Eliminado)
	 VALUES (N'wgamarra@unfv.edu.pe', N'WABIAFMATwBuAG8ASwAyAEAAMgAwADEANgA=', 'TLS', 'smtp.office365.com', 587, GETDATE(), 1, 0)
GO





/* -------------------------------- TC_TipoDocumento ------------------------------------ */

INSERT INTO TC_TipoDocumento (C_DocCod, T_DocDesc, B_Habilitado) VALUES (N'RR', N'RESOL. RECTORAL', 1);
INSERT INTO TC_TipoDocumento (C_DocCod, T_DocDesc, B_Habilitado) VALUES (N'RF', N'RESOL. DE FACULTAD', 1);
INSERT INTO TC_TipoDocumento (C_DocCod, T_DocDesc, B_Habilitado) VALUES (N'RD', N'RESOL. DIRECTORAL', 1);
INSERT INTO TC_TipoDocumento (C_DocCod, T_DocDesc, B_Habilitado) VALUES (N'PR', N'PROVEIDO', 1);
INSERT INTO TC_TipoDocumento (C_DocCod, T_DocDesc, B_Habilitado) VALUES (N'OF', N'OFICIO', 1);
INSERT INTO TC_TipoDocumento (C_DocCod, T_DocDesc, B_Habilitado) VALUES (N'OB', N'OBSERVACION', 1);
INSERT INTO TC_TipoDocumento (C_DocCod, T_DocDesc, B_Habilitado) VALUES (N'RC', N'RESOL. VRAC', 1);
INSERT INTO TC_TipoDocumento (C_DocCod, T_DocDesc, B_Habilitado) VALUES (N'RA', N'RESOL. VRAD', 1);
INSERT INTO TC_TipoDocumento (C_DocCod, T_DocDesc, B_Habilitado) VALUES (N'AC', N'ACUERDO CONSEJO UNIV', 1);
INSERT INTO TC_TipoDocumento (C_DocCod, T_DocDesc, B_Habilitado) VALUES (N'MM', N'MEMORANDO', 1);
GO


/* -------------------------------- TC_TipoResolucion ------------------------------------ */

INSERT INTO TC_TipoResolucion (C_ResolucionCod,T_ResolucionDesc,B_Habilitado) VALUES (N'RD', N'RESOLUCION DIRECTORAL', 1)
INSERT INTO TC_TipoResolucion (C_ResolucionCod,T_ResolucionDesc,B_Habilitado) VALUES (N'RR', N'RESOLUCION RECTORAL', 1)
INSERT INTO TC_TipoResolucion (C_ResolucionCod,T_ResolucionDesc,B_Habilitado) VALUES (N'RF', N'RESOLUCION DE FACULTAD', 1)
GO


/* -------------------------------- TC_CuotaPago ------------------------------------ */
INSERT INTO TC_TipoPeriodo (T_TipoPerDesc, I_Prioridad, B_Habilitado, B_Eliminado) VALUES (N'MATRICULA INGRESANTE', 1, 1, 0)
INSERT INTO TC_TipoPeriodo (T_TipoPerDesc, I_Prioridad, B_Habilitado, B_Eliminado) VALUES (N'MATRICULA REGULAR', 1, 1, 0)
INSERT INTO TC_TipoPeriodo (T_TipoPerDesc, I_Prioridad, B_Habilitado, B_Eliminado) VALUES (N'PEN.MA-ING-EUPG', 1, 1, 0)
INSERT INTO TC_TipoPeriodo (T_TipoPerDesc, I_Prioridad, B_Habilitado, B_Eliminado) VALUES (N'PEN.MA-ING-EUPG', 1, 1, 0)
INSERT INTO TC_TipoPeriodo (T_TipoPerDesc, I_Prioridad, B_Habilitado, B_Eliminado) VALUES (N'PEN.MA-REG-EUPG', 1, 1, 0)
INSERT INTO TC_TipoPeriodo (T_TipoPerDesc, I_Prioridad, B_Habilitado, B_Eliminado) VALUES (N'PEN.DO-ING-EUPG', 1, 1, 0)
INSERT INTO TC_TipoPeriodo (T_TipoPerDesc, I_Prioridad, B_Habilitado, B_Eliminado) VALUES (N'PEN.DO-REG-EUPG', 1, 1, 0)
GO



/*------------------------------------ Dependencias ------------------------------------*/
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('000000','0000000000','ADMINISTRACION CENTRAL',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('010000','03000OGREC','RECTORADO',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('010007','03091APREC','OFICINA DE ACREDITACION',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('010100','03010OCREC','OFICINA GENERAL DE AUDITORIA',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('010200','03020ASREC','OFICINA CENTRAL DE PLANIFICACION',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('010300','03040RNREC','OFICINA CENTRAL DE RELACIONES NACIONALES E INTERNACIONES',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('010400','03030ASREC','OFICINA CENTRAL JURIDICO LEGAL',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('010500','03050ASREC','SECRETARIA GENERAL',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('010600','03060APREC','OFICINA CENTRAL DE COMUNICACIËN E IMAGEN INSTITUCIONAL',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('010700','03070APREC','OFICINA CENTRAL DE BIENESTAR UNIVERSITARIO',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('010800','03080APREC','CENTRO UNIVERSITARIO DE COMPUTO E INFORMATICA',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('010901','03140DCREC','CENTRO PRE UNIVERSITARIO VILLARREAL',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('010902','04010ODREC','EDITORIAL UNIVERSITARIA',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('011000','03100DCREC','ESCUELA UNIVERSITARIA DE POST GRADO',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('011100','','CENTRO UNIVERSITARIO INVESTIGACION Y PROYECCION NACIONAL',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('011104','04020ODREC','FONDO DOCUMENTARIO DE LA CULTURA PERUANA',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('011200','','CENTRO UNIVERSITARIO RELACION, GESTION Y ACCION SOCIAL',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('011300','03130DCREC','CENTRO DE EXTENSION UNIVERSITARIA Y PROYECCION SOCIAL',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('011302','04060APVAC','INSTITUTO DE IDIOMAS',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('011400','03110DCREC','ESCUELA UNIVERSITARIA DE EDUCACION .A DISTANCIA',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('011500','03120DCREC','CENTRO UNIVERSITARIO DE PRODUCCION DE BIENES Y SERVICIOS',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('020000','04000OGVAC','VICE RECTORADO ACADEMICO',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('020100','04010APVAC','OFICINA CENTRAL DE ADMISION',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('020200','04020APVAC','OFICINA CENTRAL DE ASUNTOS ACADEMICOS',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('020300','04030APVAC','OFICINA CENTRAL DE INVESTIGACION',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('020400','03150DCREC','CENTRO CULTURAL FEDERICO VILLARREAL',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('020500','04040APVAC','INSTITUTO CENTRAL DE RECREACION EDUCACION FISICA Y DEPORTES',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('020600','04050APVAC','OFICINA CENTRAL DE REGISTRO CENTRAL Y CENTRO DE COMPUTO',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('030000','05000OGVAD','VICE RECTORADO ADMINISTRATIVO',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('030100','05020APVAD','OFICINA CENTRAL DE RECURSOS HUMANOS',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('030200','05030APVAD','OFICINA CENTRAL DE LOGISTICA Y SERVICIOS GENERALES',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('030300','05010APVAD','OFICINA CENTRAL ECONOMICO FINANCIERA',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('030500','05040APVAD','OFICINA DE INFRAESTRUCTURA Y DESARROLLO',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('039003','05050APVAD','OFICINA DE PATRIMONIO',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('100000','06020OLFAC','ARQUITECTURA Y URBANISMO',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('110000','06010OLFAC','ADMINISTRACION',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('120000','06030OLFAC','CIENCIAS ECONOMICAS',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('130000','06040OLFAC','CIENCIAS FINANCIERAS Y CONTABLES',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('140000','06050OLFAC','CIENCIAS NATURALES Y MATEMATICA',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('150000','06060OLFAC','CIENCIAS SOCIALES',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('160000','06090OLFAC','HUMANIDADES',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('170000','06070OLFAC','DERECHO Y CIENCIA POLITICA',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('180000','06080OLFAC','EDUCACION',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('190000','06100OLFAC','INGENIERIA CIVIL',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('200000','06120OLFAC','INGENIERIA GEOGRAFICA Y AMBIENTAL',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('210000','06130OLFAC','INGENIERIA INDUSTRIAL Y SISTEMAS',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('220000','06140OLFAC','MEDICINA "HIPOLITO UNANUE"',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('230000','06150OLFAC','OCEANOGRAFIA, PESQUERIA Y CC.AA.',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('240000','06160OLFAC','ODONTOLOGIA',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('250000','06170OLFAC','PSICOLOGIA',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('260000','06180OLFAC','TECNOLOGIA MEDICA',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('270000','06110OLFAC','INGENIERIA ELECTRONICA E INFORMATICA',1,0)
INSERT INTO TC_DependenciaUNFV (C_DepCod, C_DepCodPl, T_DepDesc, B_Habilitado, B_Eliminado) VALUES ('040000','06000OGVRI','VICERRECTORADO DE INVESTIGACION',1,0)
GO

/*------------------------------------ Facultad ------------------------------------*/

INSERT INTO TC_Facultad (C_CodFac,T_FacDesc, B_Habilitado, B_Eliminado) VALUES ('AU','ARQUITECTURA Y URBANISMO',1,0)
INSERT INTO TC_Facultad (C_CodFac,T_FacDesc, B_Habilitado, B_Eliminado) VALUES ('IC','INGENIERIA CIVIL',1,0)
INSERT INTO TC_Facultad (C_CodFac,T_FacDesc, B_Habilitado, B_Eliminado) VALUES ('IN','INGENIERIA INDUSTRIAL Y DE SISTEMAS',1,0)
INSERT INTO TC_Facultad (C_CodFac,T_FacDesc, B_Habilitado, B_Eliminado) VALUES ('OP','OCEANOGRAFIA,PESQUERIA Y C.ALIMENTARIAS',1,0)
INSERT INTO TC_Facultad (C_CodFac,T_FacDesc, B_Habilitado, B_Eliminado) VALUES ('IG','ING. GEOGRAFICA, AMBIENTAL Y ECOTURISMO',1,0)
INSERT INTO TC_Facultad (C_CodFac,T_FacDesc, B_Habilitado, B_Eliminado) VALUES ('CE','CIENCIAS ECONOMICAS',1,0)
INSERT INTO TC_Facultad (C_CodFac,T_FacDesc, B_Habilitado, B_Eliminado) VALUES ('CN','CIENCIAS NATURALES Y MATEMATICA',1,0)
INSERT INTO TC_Facultad (C_CodFac,T_FacDesc, B_Habilitado, B_Eliminado) VALUES ('DP','DERECHO Y CIENCIA POLITICA',1,0)
INSERT INTO TC_Facultad (C_CodFac,T_FacDesc, B_Habilitado, B_Eliminado) VALUES ('CS','CIENCIAS SOCIALES',1,0)
INSERT INTO TC_Facultad (C_CodFac,T_FacDesc, B_Habilitado, B_Eliminado) VALUES ('PS','PSICOLOGIA',1,0)
INSERT INTO TC_Facultad (C_CodFac,T_FacDesc, B_Habilitado, B_Eliminado) VALUES ('ED','EDUCACION',1,0)
INSERT INTO TC_Facultad (C_CodFac,T_FacDesc, B_Habilitado, B_Eliminado) VALUES ('CA','CIENCIAS ADMINISTRATIVAS',1,0)
INSERT INTO TC_Facultad (C_CodFac,T_FacDesc, B_Habilitado, B_Eliminado) VALUES ('CC','CIENCIAS FINANCIERAS Y CONTABLES',1,0)
INSERT INTO TC_Facultad (C_CodFac,T_FacDesc, B_Habilitado, B_Eliminado) VALUES ('CP','DESARROLLO DE LA ECONOMIA SOCIAL',1,0)
INSERT INTO TC_Facultad (C_CodFac,T_FacDesc, B_Habilitado, B_Eliminado) VALUES ('MH','MEDICINA "HIPOLITO UNANUE"',1,0)
INSERT INTO TC_Facultad (C_CodFac,T_FacDesc, B_Habilitado, B_Eliminado) VALUES ('CD','ODONTOLOGIA',1,0)
INSERT INTO TC_Facultad (C_CodFac,T_FacDesc, B_Habilitado, B_Eliminado) VALUES ('TM','TECNOLOGIA MEDICA',1,0)
INSERT INTO TC_Facultad (C_CodFac,T_FacDesc, B_Habilitado, B_Eliminado) VALUES ('CI','COORDINACION INTERPROFESIONAL',1,0)
INSERT INTO TC_Facultad (C_CodFac,T_FacDesc, B_Habilitado, B_Eliminado) VALUES ('AD','ADMINISTRACION',1,0)
INSERT INTO TC_Facultad (C_CodFac,T_FacDesc, B_Habilitado, B_Eliminado) VALUES ('HU','HUMANIDADES',1,0)
INSERT INTO TC_Facultad (C_CodFac,T_FacDesc, B_Habilitado, B_Eliminado) VALUES ('IE','INGENIERIA ELECTRONICA E INFORMATICA',1,0)
INSERT INTO TC_Facultad (C_CodFac,T_FacDesc, B_Habilitado, B_Eliminado) VALUES ('ET','ESCUELA UNIVER. DE EDUCACION A DISTANCIA',1,0)
INSERT INTO TC_Facultad (C_CodFac,T_FacDesc, B_Habilitado, B_Eliminado) VALUES ('EP','ESCUELA UNIVERSITARIA DE POSTGRADO',1,0)
INSERT INTO TC_Facultad (C_CodFac,T_FacDesc, B_Habilitado, B_Eliminado) VALUES ('CV','COORDINACION INTERPROFESIONAL',1,0)
GO

/*------------------------------------ Escuela ------------------------------------*/

INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('AR','ARQUITECTURA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('UR','URBANISMO','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('DI','DISEÑO INDUSTRIAL','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('IC','ING. CIVIL','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('IN','ING. INDUSTRIAL','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('SI','ING. DE SISTEMAS','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('AI','ING. AGROINDUSTRIAL','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('TP','ING. DE TRANSPORTES','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('AC','INGENIERIA EN ACUICULTURA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('AL','INGENIERIA ALIMENTARIA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('IP','INGENIERIA PESQUERA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('IG','INGENIERIA GEOGRAFICA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('EC','ECONOMIA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('BI','BIOLOGIA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('QU','QUIMICA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('FI','FISICA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('MA','MATEMATICA Y ESTADISTICA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('DE','DERECHO','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('PL','CIENCIA POLITICA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('SO','SOCIOLOGIA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('HS','HISTORIA Y ARQUEOLOGIA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('SS','TRABAJO SOCIAL','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('CM','CIENCIAS DE LA COMUNICACION','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('SC','PSICOLOGIA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('EI','EDUCACION INICIAL','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('EP','EDUCACION PRIMARIA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('CA','COMPLEMENTACION ACADEMICA (PROCAE)','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('ES','EDUCACION SECUNDARIA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('EF','EDUCACION FISICA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('AD','ADMINISTRACION','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('FC','CONTABILIDAD','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('CO','COOPERATIVISMO','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('ME','MEDICINA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('EN','ENFERMERIA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('NU','NUTRICION','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('LA','LABORATORIO Y ANATOMIA PATOLOGICA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('RH','TERAPIAS DE REHABILITACION','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('RI','RADIO IMAGEN','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('SA','SALUD','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('MG','MAESTRIA','M',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('DR','DOCTORADO','D',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('SE','SEGUNDA ESPECIALIZACION','S',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('EG','ESTUDIOS GENERALES','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('MV','CONVENIO ENFERMERIA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('TC','TECNICO EN CONTABILIDAD','C',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('TA','CONTROL SANITARIO DE ALIMENTOS','C',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('TJ','SECRETARIADO JUDICIAL','C',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('TO','TOPOGRAFIA Y GEODESIA','C',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('TB','INGENIERIA PESQUERA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('TT','ECOTURISMO','C',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('TE','COMERCIO EXTERIOR','C',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('TM','MERCADOTECNIA','C',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('TI','INGENIERIA ALIMENTARIA','C',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('AG','ESTUDIOS GENERALES (AR-UR-DIR)','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('OD','ODONTOLOGIA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('VV','VARIOS','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('TD','DISEÑO DE INTERIORES','C',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('TU','ORDENAMIENTO URBANO','C',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('SE','SEGUNDA ESPECIALIDAD','S',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('MD','MAGISTER Y DOCTORADO','M',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('DS','DESARROLLO SOCIAL Y MUNICIPAL','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('DC','DESARROLLO COMUNAL','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('IA','INGENIERIA AMBIENTAL','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('PT','ADMINISTRACION PRIVADA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('PG','ADMINISTRACION PUBLICA Y GESTION SOCIAL','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('PR','PROCUNED','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('TB','INGENIERIA PESQUERA','C',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('TV','ACUICULTURA','C',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('LL','LINGUISTICA Y LITERATURA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('HI','HISTORIA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('AA','ANTROPOLOGIA Y ARQUEOLOGIA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('EC','EDUCACION FISICA (CARRERAS CORTAS)','C',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('IL','INGENIERIA ELECTRONICA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('IF','INGENIERIA INFORMATICA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('OB','OBSTETRICIA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('SE','POST GRADO (SEGUNDA ESPECIALIDAD)','S',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('LI','----------------','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('PC','PROGRAMA DE COMPLEMENTACION FAP','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('SE','POST GRADO (SEGUNDA ESPECIALIDAD)','',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('DR','DOCTORADO','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('IM','INGENIERIA DE MECATRONICA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('IT','INGENIERIA DE TELECOMUNICACIONES','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('MG','MAESTRIA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('GE','GEOLOGIA','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('FR','----------------','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('FI','FILOSOFIA','',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('PL','PROLICED','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('SE','SEGUNDA ESPECIALIDAD','',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('ET','INGENIERIA EN ECOTURISMO','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('TN','ADM. DE TURISMO Y DE NEG.INTERNACIONALES','L',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('SI','----------------','D',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('PT','----------------','D',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('FC','----------------','D',1,0)
INSERT INTO TC_Escuela (C_CodEsc, T_EscDesc, C_Tipo, B_Habilitado, B_Eliminado) VALUES ('EC','----------------','D',1,0)


/*--------------------------- Especialidad ----------------------------------------*/

INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AP','ANATOMIA PATOLOGICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AS','ANESTESIOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('BQ','BIOQUIMICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CA','CARDIOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CC','CIRUGIA DE CABEZA Y CUELLO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CG','CIRUGIA GENERAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CL','CIRUGIA PLASTICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CP','CIRUGIA PEDIATRICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CT','CIRUGIA DE TORAX Y CARDIOVASCULAR',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EN','ENDOCRINOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GA','GASTROENTEROLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GO','GINECOLOGIA Y OBSTETRICIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('MF','MEDICINA FISICA Y REHABILITACION',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('MI','MEDICINA INTERNA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('MN','MEDICINA NUCLEAR',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('MT','MEDICINA INTENSIVA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('NC','NEUROCIRUGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('NE','NEUROLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('NF','NEFROLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('NM','NEUMOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('OF','OFTALMOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('ON','ONCOLOGIA MEDICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('OT','OTORRINOLARINGOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PC','PATOLOGIA CLINICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PE','PEDIATRIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('RA','RADIOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TR','TRAUMATOLOGIA Y ORTOPEDIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('UR','UROLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CU','CIENCIAS DEL URBANISMO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CR','CONSERV. Y REST. DE MONUMENTOS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TU','TRANSPORTE URBANO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('VI','VIVIENDA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AN','ANDRAGOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DU','DOCENCIA UNIVERSITARIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GG','GESTION GUBERNAMENTAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AG','ADMINISTRACION Y GESTION PUBLICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AE','ADMINISTRACION DE LA EDUCACION',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AS','ADMINISTRACION DE LA SALUD',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CS','GERENCIA EN CONSTRUCCION',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TC','TRANSPORTES Y COMUNICACIONES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AC','ACUICULTURA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('MR','CIENCIAS DEL MAR',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TA','TECNOLOGIA DE ALIMENTOS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PR','MAEST.EN ING.IND.CON MENCION EN PRODUCC.',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('BQ','BIOLOGIA Y QUIMICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('FL','FORMACION LABORAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('FM','MATEMATICA Y FISICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('HG','HISTORIA Y GEOGRAFIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('LL','LENGUA Y LITERATURA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PE','PSICOLOGIA EDUCACIONAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PC','PSICOLOGIA CLINICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('SO','SOCIOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('MA','MATEMATICA APLICADA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('BA','BIOLOGIA APLICADA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EC','ECONOMIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('FI','CIENCIAS FINANCIERAS Y CONTABLES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('FI','FINANZAS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('HP','HOSPITAL POLICIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('HN','HOSPITAL DEL NIÑO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('HM','HOSPITAL MILITAR',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AP','ADMINISTRACION PRIVADA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TC','TECNICA COMERCIAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DP','DERECHO PENAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DC','DERECHO CIVIL Y COMERCIAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AU','ARQUITECTURA Y/O URBANISMO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EG','ESTUDIOS GENERALES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TR','EN TRANSPORTES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DE','DERMATOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('HC','HEMATOLOGIA CLINICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PQ','PSIQUIATRIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('MG','MEDICINA GENERAL INTEGRAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GE','GERIATRIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CO','CIRUGIA GENERAL Y ONCOLOGICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('SP','SALUD PUBLICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('VV','VARIOS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('SC','PSICOLOGIA COMUNITARIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('LI','PROCAE LIMA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('HI','HIDROBIOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CM','CONSERV. DE MONUM. HIST. Y ART.',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AD','ADMINISTRACION',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IC','ICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CH','CHINCHA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('HU','HUANUCO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('HV','HUANCAVELICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PU','PUQUIO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TI','TINTA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AU','AUDITORIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('OP','OPTOMETRIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('RI','RADIOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TL','TERAPIA DE LENGUAJE',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TF','TERAPIA FISICA Y REHABILITACION',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EP','EPIDEMIOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GA','GESTION AMBIENTAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AE','ADMINISTRACION EDUCATIVA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AU','ADMINISTRACION UNIVERSITARIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DO','DERECHO CONSTITUCIONAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GP','GERENCIA DE PROYECTOS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GE','GESTION ECONOMICA EMPRESARIAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CV','ADMINISTRACION (M. TRABAJO-ESAP)',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('ES','DOCENCIA E INVEST. EN ESTOMATOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AG','ADMINISTRACION GUBERNAMENTAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AM','ADMINISTRACION MUNICIPAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AC','ADMINISTRACION COMUNITARIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CO','ADMINISTRACION DE COOPERATIVAS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AE','ADMINISTRACION DE EMPRESAS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AT','ADMINISTRACION DE TURISMO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('NI','NEGOCIOS INTERNACIONALES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('MT','MERCADOTECNIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CS','CONSTRUCCION',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EC','INGENIERIA ECONOMICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('MT','MODIFIC. Y TERAPIA DEL COMPORTAMIENTO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('FV','FARMACO-DEPENDENCIA Y VIOLENCIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('UR','MAESTRIA EN URBANISMO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('LS','TECNOLOGIA DE LABORATORIOS DE SALUD',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AS','ADMINISTRACION DE SERVICIOS DE SALUD',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('RS','REHABILITACION EN SALUD',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TV','CULTIVOS ACUICOLAS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TB','JEFATURA DE BAHIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TI','INDUSTRIAS ALIMENTARIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TE','TECNOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('SI','INGENIERIA DE SISTEMAS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AO','AUDITORIA OPERATIVA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GM','GESTION MUNICIPAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('FI','FILOSOFIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('LI','LINGUISTICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('LT','LITERATURA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('HI','HISTORIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AN','ANTROPOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AR','ARQUEOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('FU','FUTBOL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('NA','NATACION',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('VO','VOLEYBOL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GR','GIMNASIA RITMICA Y DEPORTIVA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AT','ATLETISMO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('BA','BASQUETBOL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('RT','RADIOTERAPIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IP','INGENIERIA PESQUERA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CP','CIENCIA POLITICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('ES','ESTADISTICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('MA','MATEMATICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EA','EDUCACION AMBIENTAL Y DESARROLLO SOSTENI',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EM','ENSEÑANZA MODERNA DE LA MATEMATICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AM','ACUICULTURA MARINA Y CONTINENTAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DS','DEPORTES Y SALUD',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GP','GESTION PUBLICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DS','GESTION PARA EL DESARROLLO SOCIAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AI','AUDITORIA INTEGRAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GE','GERENCIA EDUCATIVA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('SA','PSICOLOGIA DE LA SALUD',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PI','GERENCIA DE PROYECTOS DE INGENIERIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CM','GERENCIA DE LA CONSTRUCCION MODERNA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('OP','GESTION DE OPERACIONES Y PRODUCTIVIDAD',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AG','TECNOLOGIA DE ALIMENTOS Y AGROINDUSTRIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TS','ANALISIS DE SISTEMAS - CARRERA CORTA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PP','ADMINISTRACION',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('NP','NEFROLOGIA PEDIATRICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('NT','NEONATOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GP','GASTROENTEROLOGIA PEDIATRICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GS','ADMINISTRACION Y GERENCIA SOCIAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IE','INVESTIGACION Y ENSEÑANZA DEL ESPAÑOL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GT','GERONTOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('HS','HISTORIA SOCIAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CA','CONDUCTA ADICTIVA Y VIOLENCIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DE','DERECHO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IN','INGENIERIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('SC','PSICOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('SE','SALUD PUBLICA CON MENCION EN EPIDEMIOLOG',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('LD','LABORATORIOS DE SALUD',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DC','DISEÑO Y EVALUACION CURRICULAR',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CP','DESARROLLO ECONOMICO SOCIAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CO','CONTABILIDAD',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('OD','ODONTOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CF','AUDITORIA CONTABLE Y FINANCIERA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CI','COMUNICACION INTERACTIVA CON MENCION EN PRODUCCION AUDIOVISUAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DE','DERECHO EMPRESARIAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('MM','MEDICINA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('SH','SALUD PUBLICA CON MENCION EN GESTION HOSPITALARIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('SR','SALUD PUBLICA CON MENCION EN SALUD REPRODUCTIVA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TF','TERAPIA FISICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('LH','LINGÜISTICA HISPANICA CON MENCION EN INVESTIGACION Y ENSEÑANZA DEL ESPAÑOL COMO LENGUA I',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('ED','EDUCACION',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('NU','NUTRICION',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GF','GEOFISICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PP','PSICOTERAPIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('RD','RETARDO EN EL DESARROLLO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PA','PROBLEMAS DE APRENDIZAJE',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PF','PSICOTERAPIA DE PAREJA Y FAMILIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('FP','FILOSOFIA Y CIENCIAS SOCIALES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TS','TERAPIAS SEXUALES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('SF','EDUCACION SEXUAL Y FAMILIAR',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IP','INTERVENCION PSICOPEDAGOGICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('FS','PSICOLOGIA FORENSE Y CRIMINALISTICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DO','COMPORTAMIENTO Y DESARROLLO ORGANIZACIONAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('ER','ENDOCRINOLOGIA PEDIATRICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('RG','REUMATOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AA','ADMINISTRACION DEL CAPITAL SOCIAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AT','AGROINDUSTRIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('UA','ARQUITECTURA Y/O URBANISMO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CR','CONSERVACION Y RESTAURACION DE MONUMENTOS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GB','ADMINISTRACION Y GESTION PUBLICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('SD','ADMINISTRACION DE LA SALUD',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EO','CIENCIAS DE LA COOPERACION CON MENCION EN ADMINISTRACION Y FINANZAS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CS','GERENCIA DE LA CONSTRUCCION',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TR','TRANSPORTES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PR','INGENIERIA INDUSTRIAL CON MENCION EN GESTION DE OPERACIONES Y PRODUCTIVIDAD',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AR','ARQUITECTURA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('UR','URBANISMO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('ES','DOCENCIA E INVESTIGACION EN ESTOMATOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GP','GERENCIA EN PROYECTOS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CV','ADMINISTRACION (M.TRABAJO-ESAP)',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('MT','MODIFICACION Y TERAPIA DEL COMPORTAMIENTO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CC','ADMINISTRACION DE LA EDUCACION',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EA','EDUCACION AMBIENTAL Y DESARROLLO SOSTENIBLE',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PL','GESTION PUBLICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('SL','GESTION PARA EL DESARROLLO SOCIAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EG','GERENCIA EDUCATIVA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('NC','NEUROCIENCIAS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EI','INGENIERIA ECONOMICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('SE','SALUD PUBLICA CON MENCION EN EPIDEMIOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DL','DERECHO LABORAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GF','GERENCIA DE FAMILIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GD','GESTION MUNICIPAL Y DESARROLLO LOCAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GN','GESTION Y ADMINISTRACION DE LA EDUCACION',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('MI','MARKETING Y NEGOCIOS INTERNACIONALES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PO','PSICOLOGIA ORGANIZACIONAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('RB','REHABILITACION',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TM','TECNOLOGIA MEDICA CON MENCION EN MICROBIOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('RD','TECNOLOGIA MEDICA CON MENCION EN RADIOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('LP','LITERATURA CON MENCION EN LITERATURA PERUANA E HISPANOAMERICANA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('FC','FILOSOFIA Y CONCEPCIONES DEL MUNDO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DA','GESTION DE ALTA DIRECCION',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IT','INGENIERIA ELECTRONICA CON MENCION EN TELEMATICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PB','GESTION DE POLITICAS PUBLICAS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DN','DERECHOS DEL NIÑO Y POLITICAS PUBLICAS PARA LA INFANCIA Y LA ADOLESCENCIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('MD','MEDIO AMBIENTE Y DESARROLLO SOSTENIBLE',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GC','GESTION Y CONDUCCION EN SALUD',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('LC','LABORATORIO CLINICO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('MB','MICROBIOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('MC','MEDICINA COMUNITARIA Y FAMILIAR',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TT','TURISMO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GL','GERENCIA SOCIAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PA','POLIDISCIPLINARIA EN ARQUITECTURA Y URBA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PD','POLIDISCIPLINARIA EN DISEÑO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('ME','MEDICINA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('ID','IBEROAMERICANA ON-LINE EN DROGODEPENDENCIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IC','INGENIERIA CON MENCION EN CONSTRUCCION',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('ID','CON MENCION EN INGENIERIA INDUSTRIAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IS','CON MENCION EN INGENIERIA DE SISTEMAS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IA','CON MENCION EN INGENIERIA AGROALIMENTARIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('ET','ING.GEOGRAFICA CON MENCION EN ECOTURISMO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IG','INGENIERIA GEOGRAFICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('SS','GESTION EN SEGURIDAD SOCIAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('MS','MEDICINA LEGAL Y CIENCIAS FORENSES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('OM','ORDENAC. DEL TERRITORIO Y MEDIO AMBIENTE',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PS','PSICOLOGIA SOCIAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PE','PSICOLOGIA EDUCATIVA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CO','CIENCIAS DE LA COOPERACION',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('HR','HISTORIA REGIONAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PG','POLITICA Y GESTION PUBLICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DG','DIPLO.ACAD.EN DROG.FORMACION DE RRHH.',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EL','DIPLO.ACAD.EN ESTIMULACION TEMPRANA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('MH','ACADEMICA EN CONSTRUCCION Y RESTAURACION DE MONUMENTOS HISTORICOS Y ARTISTICOS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AQ','ACADEMICA EN ARQUITECTURA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AB','ACADEMICA EN URBANISMO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CT','CONSTRUCCION',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GI','DIPLOMADO EN: GESTION DE GERENCIA INSTIT',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IM','DIPLOMADO EN: INTERCULTURALIDAD Y MATERI',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EE','MEDICINA EN EMERGENCIAS Y DESASTRES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('FN','MEDICINA FAMILIAR Y COMUNITARIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('ST','SOCIOLOGIA DEL DELITO Y LAS CONDUC.DESV.',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AL','ANTROPOLOGIA POLITICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('ER','ECON.CON MENCION EN DESARROLLO ECON.REG.',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CN','CRIMINALISTICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DJ','DERECHO JUDICIAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GD','DIPLOMADO EN: ARCHIVOS Y GESTION DOCUMEN',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DB','ADMINISTRACION PUBLICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('MK','MARKETING',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TO','TURISMO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('NS','CIENCIAS SOCIALES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('VD','INGENIERIA CON MENCION EN PREVENCION Y MANEJO DE DESASTRES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CL','PSICOLOGIA CLINICA Y DE LA SALUD',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('OR','PSICOLOGIA ORGANIZACIONAL Y RECURSOS HUMANOS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PV','PREVENCION DE LAS ADICCIONES Y VIOLENCIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EP','EDUCACION PRIMARIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EE','EDUCACION ESPECIAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TG','TECNOLOGIA Y GESTION EMPRESARIAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CI','COMPUTACION E INFORMATICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CN','CIENCIAS NATURALES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('HS','CIENCIAS HISTORICO SOCIALES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PN','PLANIFICACION ECONOMICA REGIONAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GI','GESTION DE PROYECTOS PARA INVERSION PRIVADA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DR','DROGODEPENDENCIAS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PT','PSICOLOGIA EDUC.CON MENCION EN PROBL.DE APRENDIZAJE,TUTORIA Y ORIENTACION EDUCATIVA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PF','PSICOLOGIA FORENSE Y CRIMINALISTICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PS','PSICOLOGIA SOCIAL CON MENCION EN GESTION DE PROYECTOS DE DESARROLLO SOCIAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('SX','SEXUALIDAD HUMANA, SALUD SEXUAL Y REPRODUCTIVA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TG','TERAPIA COGNITIVO-CONDUCTUAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('ID','IDIOMAS:INGLES Y FRANCES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('FD','EDUCACION FISICA Y CIENCIAS DEL DEPORTE',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EI','EDUCACION INICIAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('BM','GENETICA Y BIOLOGIA MOLECULAR',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IR','INGENIERIA INDUSTRIAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('NL','CIENCIAS DE LOS ALIMENTOS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IV','INGENIERIA CIVIL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('NB','NEGOCIOS BANCARIOS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DI','DIRECCION Y GESTION DE INSTITUCIONES DE MICRO FINANZAS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CE','COSTOS Y PRESUPUESTOS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('RO','GERENCIA DE ORGANIZACIONES POLITICAS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DM','ADMINISTRACION DE PEQUEÑAS Y MEDIANAS EMPRESAS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DF','DEFENSA NACIONAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('FT','TERAPIA FAMILIAR SISTEMICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('KC','MARKETING EN COMUNICACIONES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GR','GESTION EN ENFERMERIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IL','IDIOMAS:INGLES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('FR','IDIOMAS:FRANCES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AI','ALERGIA E INMUNOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CS','PSICOLOGIA CLINICA Y DE LA SALUD',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PS','PSICOTERAPIA FAMILIAR SISTEMICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PH','PSICOTERAPIA HUMANISTA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TC','TERAPIA COGNITIVO CONDUCTUAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DA','DIPLOMADO EN ADICCIONES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TT','ADMINISTRACION DE TURISMO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('NN','NEGOCIOS INTERNACIONALES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GY','GERENCIA DE PROYECTOS EMPRESARIALES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GU','GESTION DE INVERSION PUBLICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GO','GESTION ECONOMICA REGIONAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TB','TRIBUTACION',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('ED','EDUCACION ANDRAGOGICA (EDUCACION DE ADULTOS)',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DD','DERECHO CON MENCION EN ADUANAS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DF','DERECHO CON MENCION EN POLITICA FISCAL Y TRIBUTACION',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DV','DERECHO PRIVATIVO MILITAR',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GV','GESTION DE LA BIODIVERSIDAD',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('II','INGENIERIA AGROINDUSTRIAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IA','INGENIERIA AMBIENTAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('NS','INGENIERIA DE SISTEMAS CON MENCION EN GESTION DE TECNOLOGIAS DE LA INFORMACION',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IM','INGENIERIA DE SISTEMAS CON MENCION EN INGENIERIA DE SOFTWARE',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IN','INGENIERIA DE TRANSPORTE',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IC','INGENIERIA EN CATASTRO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IU','INGENIERIA EN ECOTURISMO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IG','INGENIERIA EN GESTION DE MONTAÑAS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('VV','INGENIERIA EN VULNERABILIDAD DEL AMBIENTE URBANO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IR','INGENIERIA GEOGRAFICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('ZN','ZONIFICACION ECOLOGICA Y ECONOMICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('FS','FISIOTERAPIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EL','ENSAYO LATINOAMERICANO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IL','INGENIERIA AMBIENTAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IP','INGENIERIA INDUSTRIAL CON MENCION EN GESTION DE LA PRODUCCION',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GE','GEOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EC','ENFERMERIA EN CARDIOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EQ','ENFERMERIA EN CENTRO QUIRURGICO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EI','ENFERMERIA EN CUIDADOS INTENSIVOS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('ED','ENFERMERIA EN EMERGENCIAS Y DESASTRES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EG','ENFERMERIA EN GERIATRIA Y GERONTOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('ET','ENFERMERIA EN NEONATOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EP','ENFERMERIA PEDIATRICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('ES','ENFERMERIA EN SALUD MENTAL Y PSIQUIATRIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EO','ENFERMERIA EN OFTALMOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EM','ENFERMERIA EN SALUD DE LA MUJER',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EB','ENFERMERIA EN SALUD PUBLICA Y COMUNITARIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EA','ENFERMERIA EN ADMINISTRACION Y GESTION',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AL','CIENCIAS CON MENCION EN ACUICULTURA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GD','GESTION MEDIO AMBIENTAL Y DESARROLLO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DG','DOCENCIA Y GESTION UNIVERSITARIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GS','GESTION DEL BIENESTAR SOCIAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IF','INGENIERIA GEOGRAFICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DH','DIRECCION Y ORGANIZACION DE HOSPITALES Y SERVICIOS DE SALUD',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('NG','ECONOMIA Y GESTION DE LA SALUD',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PÑ','PSIQUIATRIA DEL NIÑO Y DEL ADOLESCENTE',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('MP','MEDICINA INTENSIVA PEDIATRICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('FM','FISIOTERAPIA EN EL ADULTO MAYOR',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CB','CIRUGIA BUCAL MAXILO FACIAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CD','CARIELOGIA Y ENDODONCIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('MO','MEDICINA Y PATOLOGIA ESTOMATOLOGICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('OO','ODONTOPEDIATRIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('OE','ORTODONCIA Y ORTOPEDIA MAXILAR',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('RN','PERIODONCIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('RU','RADIOLOGIA BUCAL Y MAXILO FACIAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('RR','REHABILITACION ORAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('SU','SALUD PUBLICA ESTOMATOLOGICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('NO','ODONTOLOGIA FORENSE',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('FO','FISIOTERAPIA CARDIORESPIRATORIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TP','ESTOMATOLOGIA DE PACIENTES ESPECIALES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('BC','BIOQUIMICA CLINICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EF','ENFERMERIA EN NEFROLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EL','ENFERMERIA EN GASTROENTEROLOGIA Y ENDOSCOPIA GASTROINTESTINAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('LA','LABORATORIO Y ANATOMIA PATOLOGICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CG','TECNICAS Y GESTION MEDIO AMBIENTALES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('UC','URBANISMO, CONSTRUCCION Y VALORACIONES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TI','ANTROPOLOGIA CON MENCION EN METODOLOGIA Y TECNICAS EN LA INVESTIGACION SOCIOCULTURAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GJ','GESTION DE PROGRAMAS Y POLITICAS DE INFANCIA, ADOLESCENCIA Y JUVENTUD',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GH','GESTION DE PATRIMONIO CULTURAL E INVESTIGACION HISTORICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('HU','HUMANIDADES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AA','AUTOEVALUACION Y ACREDITACION DE INSTITUCIONES EDUCATIVAS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('ES','EDUCACION PSICOMOTRIZ',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PP','PSICOPEDAGOGIA Y PROBLEMAS DEL APRENDIZAJE',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('GD','GESTION Y DIRECCION ESTRATEGICA DE INSTITUCIONES EDUCATIVAS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DI','DOCENCIA DEL IDIOMA INGLES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IE','INFORMATICA EDUCATIVA Y NUEVAS TECNOLOGIAS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EN','EDUCACION INCLUSIVA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AT','ATENCION TEMPRANA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EB','EDUCACION BASICA ALTERNATIVA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EA','EDUCACION ARTISTICA Y PROMOTORIA CULTURAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('DS','DOCENCIA SUPERIOR Y UNIVERSITARIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('ET','EDUCACION PARA EL TRABAJO Y DESARROLLO TECNOLOGICO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('NS','NEUROPSICOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('BT','BIOTECNOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TN','GESTION AMBIENTAL Y MINERA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('HB','HIDROLOGIA SUBTERRANEA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('HT','HIDROLOGIA Y GESTION DEL AGUA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('OG','ORDENAMIENTO Y GESTION DEL TERRITORIO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('RH','INGENIERIA DE RECURSOS HIDRAULICOS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('SN','SEGURIDAD INDUSTRIAL Y PROTECCION AMBIENTAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('FG','TECNOLOGIAS DE INFORMACION GEOGRAFICA (TIG)',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EU','ENFERMERIA EN NEUMOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('SM','INGENIERIA DE SISTEMAS CON MENCION EN GESTION DEL CONOCIMIENTO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('EV','EVALUACION Y ACREDITACION DE INSTITUCIONES EDUCATIVAS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('MU','GESTION MUNICIPAL Y EDUCACION',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('LV','INGENIERIA INDUSTRIAL CON MENCION EN GESTION DE LA CALIDAD Y LA PRODUCTIVIDAD',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('PM','INGENIERIA DE SISTEMAS CON MENCION EN INTELIGENCIA DE PROCESOS EMPRESARIALES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IO','INGENIERIA AGROINDUSTRIAL CON MENCION EN INGENIERIA DE PROCESOS ALIMENTARIOS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IK','INGENIERIA INDUSTRIAL CON MENCION EN MARKETING INDUSTRIAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('RF','INGENIERIA TELEMATICA Y REDES INFORMATICAS',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IS','INGENIERIA INDUSTRIAL CON MENCION EN INGENIERIA EMPRESARIAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('MP','INGENIERIA INDUSTRIAL CON MENCION EN PRODUCCION',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('SV','ESTADISTICA E INVESTIGACION CIENTIFICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('LM','DIPLOMADO EN: CULTURA DE LA IMAGEN Y LENGUAJE CINEMATOGRAFICO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('ND','EDUCACION PARA EL DESARROLLO SOSTENIBLE',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TD','DIDACTICA DE LA MATEMATICA PARA LA EDUCACION PRIMARIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AZ','DIAGNOSTICO Y TRATAMIENTO DE PROBLEMAS DE APRENDIZAJE',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('FC','PSICOLOGIA FORENSE Y CRIMINOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('SG','SALUD SEXUAL Y GENERO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('UO','UROLOGIA GENERAL Y ONCOLOGICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('OC','ONCOLOGIA PEDIATRICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('ML','MEDICINA GENERAL Y ONCOLOGICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TO','TECNOLOGIAS DE INFORMACION GEOGRAFICA Y GESTION DEL TERRITORIO',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('FC','CONTABILIDAD',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('FD','FISIOTERAPIA DEL DEPORTE',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('MR','REEDUCACION DE LA MOTRICIDAD OROFACIAL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CS','DIDACTICA DE LAS CIENCIAS SOCIALES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('LI','LICENCIATURA A DIST. EN LA ENSEÑANZA DE INGLES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('FR','LICENCIATURA A DIST. EN LA ENSEÑANZA DEL FRANCES',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('HE','HEMOTERAPIA Y BANCO DE SANGRE',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('HG','HISTOTECNOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('CT','CITOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('UP','NEUMOLOGIA PEDIATRICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('IR','TRIBUTACION',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('FQ','FISIOTERAPIA EN QUEMADOS Y CIRUGIA PLASTICA RECONSTRUCTIVA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('LI','LOGOPEDIA INFANTIL',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('MC','MICROBIOLOGIA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('RM','RESONANCIA MAGNETICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TM','TERAPIA MANUAL ORTOPEDICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('TC','TOMOGRAFIA COMPUTADA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('NU','NEUROLOGIA PEDIATRICA',1,0)
INSERT INTO TC_Especialidad (C_CodEsp, T_EspDesc, B_Habilitado, B_Eliminado) VALUES ('AG','ACUICULTURA Y GERENCIAMIENTO',1,0)
