USE BD_OCEF_MigracionTP
GO


DECLARE @I_CuotaPago int

DECLARE CUR_CP_DES CURSOR
FOR
	SELECT * FROM cp_des
OPEN CUR_CP_DES
FETCH NEXT FROM CUR_CP_DES INTO @I_CuotaPago
	
WHILE @@FETCH_STATUS = 0
BEGIN

	FETCH NEXT FROM CUR_CP_DES INTO @I_CuotaPago
END
CLOSE CUR_CP_DES
DEALLOCATE CUR_CP_DES
GO
