USE BD_OCEF_CtasPorCobrar
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_TYPE = 'PROCEDURE' AND ROUTINE_NAME = 'USP_IU_GrabarProcesosYCuentasMigracion')
	DROP PROCEDURE [dbo].[USP_IU_GrabarProcesosYCuentasMigracion]
GO



IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'B_Migrado' AND TABLE_NAME = 'TR_ObligacionAluCab')
BEGIN
ALTER TABLE TR_ObligacionAluCab
	ADD B_Migrado    bit  NOT NULL DEFAULT(0)

	UPDATE TR_ObligacionAluCab SET B_Migrado = 0
END
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'B_Migrado' AND TABLE_NAME = 'TR_ObligacionAluDet')
BEGIN
	ALTER TABLE TR_ObligacionAluDet
		ADD B_Migrado    bit  NOT NULL DEFAULT(0)

	UPDATE TR_ObligacionAluDet SET B_Migrado = 0
END
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'B_Migrado' AND TABLE_NAME = 'TRI_PagoProcesadoUnfv')
BEGIN
	ALTER TABLE TRI_PagoProcesadoUnfv
		ADD B_Migrado    bit  NOT NULL DEFAULT(0)

	UPDATE TRI_PagoProcesadoUnfv SET B_Migrado = 0
END
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'B_Migrado' AND TABLE_NAME = 'TR_PagoBanco')
BEGIN
	ALTER TABLE TR_PagoBanco
		ADD B_Migrado    bit  NOT NULL DEFAULT(0)

	UPDATE TR_PagoBanco SET B_Migrado = 0
END
GO



