SELECT CUOTA_PAGO, count(*) FROM cp_des	   GROUP BY CUOTA_PAGO HAVING COUNT(*) > 1
SELECT CUOTA_PAGO, count(*) FROM cp_des_21 GROUP BY CUOTA_PAGO HAVING COUNT(*) > 1

SELECT * FROM cp_des WHERE CUOTA_PAGO IN (
143,
330,
331,
438,
439)
ORDER BY 1 

SELECT COUNT(*) FROM cp_des
SELECT COUNT(*) FROM cp_des WHERE ELIMINADO = 1




SELECT COUNT(*) FROM cp_pri
SELECT COUNT(*) FROM cp_pri_21 WHERE ELIMINADO = 1

SELECT ID_CP, count(*) FROM cp_pri	   GROUP BY ID_CP HAVING COUNT(*) > 1
SELECT ID_CP, count(*) FROM cp_pri_21 GROUP BY ID_CP HAVING COUNT(*) > 1


SELECT * FROM cp_pri A
INNER JOIN cp_pri_21 B ON A.ID_CP = B.ID_CP



SELECT * FROM cp_pri WHERE ID_CP IN (
3899,
3898,
3897,
3896
)
ORDER BY 1