USE [master]
GO

/*  SCRIPT PARA LA CREACIÓN DE BASE DE DATOS */

CREATE DATABASE [BD_UNFV_Repositorio]
 CONTAINMENT = NONE
 ON  PRIMARY 
--( NAME = N'BD_UNFV_Repositorio', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQL_2016E\MSSQL\DATA\BD_UNFV_Repositorio.mdf' , SIZE = 10240KB , FILEGROWTH = 1024KB )
( NAME = N'BD_UNFV_Repositorio', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\BD_UNFV_Repositorio.mdf' , SIZE = 10240KB , FILEGROWTH = 1024KB )	
 LOG ON 
--( NAME = N'BD_UNFV_Repositorio_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQL_2016E\MSSQL\DATA\BD_UNFV_Repositorio.ldf' , SIZE = 6144KB , FILEGROWTH = 10%)
( NAME = N'BD_UNFV_Repositorio_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\BD_UNFV_Repositorio.ldf' , SIZE = 6144KB , FILEGROWTH = 10%)
 COLLATE Modern_Spanish_CI_AS
GO

ALTER DATABASE [BD_UNFV_Repositorio] SET COMPATIBILITY_LEVEL = 120
GO
ALTER DATABASE [BD_UNFV_Repositorio] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BD_UNFV_Repositorio] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BD_UNFV_Repositorio] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BD_UNFV_Repositorio] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BD_UNFV_Repositorio] SET ARITHABORT OFF 
GO
ALTER DATABASE [BD_UNFV_Repositorio] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BD_UNFV_Repositorio] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BD_UNFV_Repositorio] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [BD_UNFV_Repositorio] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BD_UNFV_Repositorio] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BD_UNFV_Repositorio] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BD_UNFV_Repositorio] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BD_UNFV_Repositorio] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BD_UNFV_Repositorio] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BD_UNFV_Repositorio] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BD_UNFV_Repositorio] SET DISABLE_BROKER 
GO
ALTER DATABASE [BD_UNFV_Repositorio] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BD_UNFV_Repositorio] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BD_UNFV_Repositorio] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BD_UNFV_Repositorio] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BD_UNFV_Repositorio] SET READ_WRITE 
GO
ALTER DATABASE [BD_UNFV_Repositorio] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BD_UNFV_Repositorio] SET MULTI_USER 
GO
ALTER DATABASE [BD_UNFV_Repositorio] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BD_UNFV_Repositorio] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [BD_UNFV_Repositorio] SET DELAYED_DURABILITY = DISABLED 
GO

USE [BD_UNFV_Repositorio]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [BD_UNFV_Repositorio] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO


/*	CREACIÓN DE LOGIN PARA LA BASE DE DATOS	*/

USE [master]
GO

IF NOT EXISTS (SELECT principal_id FROM sys.sql_logins WHERE name = 'UserOCEF')
BEGIN
	CREATE LOGIN [UserOCEF] WITH PASSWORD=N'123@abc', DEFAULT_DATABASE=[BD_UNFV_Repositorio], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
END
ELSE
BEGIN
	PRINT ('Ya existe el LOGIN UserOCEF en master.  Se omitió la creación')
END
GO

IF NOT EXISTS (SELECT principal_id FROM sys.sql_logins WHERE name = 'UserUNFV')
BEGIN
	CREATE LOGIN [UserUNFV] WITH PASSWORD=N'123@abc', DEFAULT_DATABASE=[BD_UNFV_Repositorio], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
END
ELSE
BEGIN
	PRINT ('Ya existe el LOGIN UserUNFV en master.  Se omitió la creación')
END
GO


/*	CREACIÓN DE USUARIO DE BASE DE DATOS	*/

USE [BD_UNFV_Repositorio]
GO

IF NOT EXISTS (SELECT uid FROM sys.sysusers WHERE name = 'UserOCEF' AND issqluser = 1)
BEGIN

	CREATE USER [UserOCEF] FOR LOGIN [UserOCEF] WITH DEFAULT_SCHEMA=[dbo]

	ALTER ROLE [db_datareader] ADD MEMBER [UserOCEF]
END
ELSE
BEGIN
	PRINT ('Ya existe el usuario UserOCEF en BD_UNFV_Repositorio. Se omitió la creación')
END
GO

IF NOT EXISTS (SELECT uid FROM sys.sysusers WHERE name = 'UserUNFV' AND issqluser = 1)
BEGIN

	CREATE USER [UserUNFV] FOR LOGIN [UserUNFV] WITH DEFAULT_SCHEMA=[dbo]

	ALTER ROLE [db_owner] ADD MEMBER [UserUNFV]

	ALTER ROLE [db_datareader] ADD MEMBER [UserUNFV]

	ALTER ROLE [db_datawriter] ADD MEMBER [UserUNFV]

END
ELSE
BEGIN
	PRINT ('Ya existe el usuario UserUNFV en BD_UNFV_Repositorio. Se omitió la creación')
END
GO