USE BD_OCEF_CtasPorCobrar
GO


SELECT BNC.I_CtaDepositoID, CP.I_CatPagoID, 1 AS B_Habilitado, 0 as B_Eliminado--, C_NumeroCuenta, CODIGO_BNC    
FROM TC_CategoriaPago CP 
	 INNER JOIN (SELECT DISTINCT I_CtaDepositoID, C_NumeroCuenta, TP_CP.CODIGO_BNC COLLATE DATABASE_DEFAULT AS CODIGO_BNC
					FROM TC_CuentaDeposito CD  
						 INNER JOIN temporal_pagos..cp_des TP_CP ON CD.C_NumeroCuenta COLLATE DATABASE_DEFAULT = TP_CP.N_CTA_CTE COLLATE DATABASE_DEFAULT
					WHERE ELIMINADO = 0 AND CODIGO_BNC IN (
							'0635','0636','0638','0670','0671','0674',
							'0675','0676','0677','0678','0679','0680',
							'0681','0682','0683','0687','0688','0689',
							'0690','0691','0692','0695','0696','0697',
							'0698')
) BNC ON CP.N_CodBanco = BNC.CODIGO_BNC
UNION
SELECT BNC.I_CtaDepositoID, CP.I_CatPagoID, 1 AS B_Habilitado, 0 as B_Eliminado--, C_NumeroCuenta, CODIGO_BNC    
FROM TC_CategoriaPago CP 
	 INNER JOIN (SELECT DISTINCT I_CtaDepositoID, C_NumeroCuenta, TP_CP.CODIGO_BNC COLLATE DATABASE_DEFAULT AS CODIGO_BNC
				 FROM TC_CuentaDeposito CD  
 				 		INNER JOIN temporal_pagos..cp_des TP_CP ON CD.C_NumeroCuenta COLLATE DATABASE_DEFAULT = TP_CP.N_CTA_CTE COLLATE DATABASE_DEFAULT
				 WHERE CODIGO_BNC IS NULL
) BNC ON CP.N_CodBanco IS NULL


SELECT CAST(TP_CD.CUOTA_PAGO AS INT) CUOTA_PAGO, I_CatPagoID, TP_CD.DESCRIPCIO, 
	   CASE ISNUMERIC(LTRIM(SUBSTRING(LTRIM(TP_CD.DESCRIPCIO),1,4))) WHEN 1 THEN SUBSTRING(LTRIM(TP_CD.DESCRIPCIO),1,4) ELSE NULL END AS I_Anio, 
	   TP_CP.ano, TP_CP.p,
	   NULL AS I_Periodo, CODIGO_BNC, FCH_VENC, PRIORIDAD, CASE C_MORA WHEN 'VERDADERO' THEN 1 WHEN 'FALSO' THEN 0 ELSE NULL END
FROM TC_CategoriaPago CP  
	  INNER JOIN temporal_pagos..cp_des TP_CD ON CP.N_CodBanco COLLATE DATABASE_DEFAULT = TP_CD.CODIGO_BNC COLLATE DATABASE_DEFAULT
	  LEFT JOIN (SELECT DISTINCT cuota_pago, ano, p FROM temporal_pagos..cp_pri WHERE eliminado = 0) TP_CP ON TP_CP.cuota_pago = TP_CD.CUOTA_PAGO
WHERE TP_CD.ELIMINADO = 0 AND CODIGO_BNC IN (
		'0635','0636','0638','0670','0671','0674',
		'0675','0678','0679','0680','0681','0682',
		'0683','0689','0690','0691','0692','0695',
		'0696','0697','0698'
		)
ORDER BY 1,2


SELECT CAST(CUOTA_PAGO AS INT) CUOTA_PAGO, I_CatPagoID, TP_CP.DESCRIPCIO, 
	   CASE ISNUMERIC(LTRIM(SUBSTRING(LTRIM(DESCRIPCIO),1,4))) WHEN 1 THEN SUBSTRING(LTRIM(DESCRIPCIO),1,4) ELSE NULL END AS I_Anio, 
	   NULL AS I_Periodo, CODIGO_BNC, FCH_VENC, PRIORIDAD, CASE C_MORA WHEN 'VERDADERO' THEN 1 WHEN 'FALSO' THEN 0 ELSE NULL END
FROM TC_CategoriaPago CP  
		INNER JOIN temporal_pagos..cp_des TP_CP ON CP.N_CodBanco COLLATE DATABASE_DEFAULT = TP_CP.CODIGO_BNC COLLATE DATABASE_DEFAULT
WHERE ELIMINADO = 0 AND CODIGO_BNC IN (
			'0637','0639','0658','0672','0673','0685'

			,'0676','0677','0687','0688'
		)
ORDER BY N_CodBanco, 1


SELECT DISTINCT N_CTA_CTE, CODIGO_BNC 
FROM temporal_pagos..cp_des
WHERE ELIMINADO = 0 AND CODIGO_BNC IN (
'0635','0636','0638','0670','0671','0674',
'0675','0676','0677','0678','0679','0680',
'0681','0682','0683','0687','0688','0689',
'0690','0691','0692','0695','0696','0697',
'0698'
)


SELECT * FROM temporal_pagos..cp_des 
WHERE ELIMINADO = 0 AND CODIGO_BNC IN (
'0637',
'0639',
'0658',
'0672',
'0673',
'0685'

,'0676','0677','0687','0688'
)
ORDER BY CODIGO_BNC



SELECT TP_CD.CUOTA_PAGO , COUNT(TP_CD.CUOTA_PAGO), ano
FROM TC_CategoriaPago CP  
	  INNER JOIN temporal_pagos..cp_des TP_CD ON CP.N_CodBanco COLLATE DATABASE_DEFAULT = TP_CD.CODIGO_BNC COLLATE DATABASE_DEFAULT
	  LEFT JOIN (SELECT DISTINCT cuota_pago, ano, p FROM temporal_pagos..cp_pri WHERE eliminado = 0) TP_CP ON TP_CP.cuota_pago = TP_CD.CUOTA_PAGO
WHERE TP_CD.ELIMINADO = 0 AND CODIGO_BNC IN (
		'0635','0636','0638','0670','0671','0674',
		'0675','0678','0679','0680','0681','0682',
		'0683','0689','0690','0691','0692','0695',
		'0696','0697','0698'
		)
		AND CAST(ano AS int) > 2015
GROUP BY TP_CD.CUOTA_PAGO, ano
HAVING COUNT(TP_CD.CUOTA_PAGO) > 1
ORDER BY 1,2


WITH TEMP_PROC (I_ProcesoID, I_CatPagoID, T_ProcesoDesc, I_Anio, N_CodBanco, D_FecVencto, I_Prioridad, B_Mora, B_Migrado, B_Habilitado, B_Eliminado)
AS
(
	SELECT CAST(TP_CD.CUOTA_PAGO AS INT) CUOTA_PAGO, I_CatPagoID, TP_CD.DESCRIPCIO, 
	   CASE ISNUMERIC(LTRIM(SUBSTRING(LTRIM(TP_CD.DESCRIPCIO),1,4))) WHEN 1 THEN SUBSTRING(LTRIM(TP_CD.DESCRIPCIO),1,4) ELSE NULL END AS I_Anio, 
	    CODIGO_BNC, FCH_VENC, PRIORIDAD, CASE C_MORA WHEN 'VERDADERO' THEN 1 WHEN 'FALSO' THEN 0 ELSE NULL END AS C_MORA,
		1 AS B_Migrado, 1 AS B_Habilitado, TP_CD.ELIMINADO
	FROM TC_CategoriaPago CP  
		  INNER JOIN temporal_pagos..cp_des TP_CD ON CP.N_CodBanco COLLATE DATABASE_DEFAULT = TP_CD.CODIGO_BNC COLLATE DATABASE_DEFAULT
	WHERE TP_CD.ELIMINADO = 0 AND CODIGO_BNC IN (
			'0635','0636','0638','0670','0671','0674',
			'0675','0678','0679','0680','0681','0682',
			'0683','0689','0690','0691','0692','0695',
			'0696','0697','0698'
			)
)

SELECT	I_ProcesoID, I_CatPagoID, T_ProcesoDesc, I_Anio, co_periodo.I_OpcionID AS I_Periodo, N_CodBanco, D_FecVencto, I_Prioridad, B_Mora, 
		B_Migrado, TEMP.B_Habilitado, TEMP.B_Eliminado
FROM	TEMP_PROC TEMP
		LEFT JOIN (SELECT DISTINCT cuota_pago, ano, p FROM temporal_pagos..cp_pri WHERE eliminado = 0) TP_CP ON TP_CP.cuota_pago = TEMP.I_ProcesoID
		LEFT JOIN TC_CatalogoOpcion co_periodo ON co_periodo.T_OpcionCod COLLATE DATABASE_DEFAULT = TP_CP.p COLLATE DATABASE_DEFAULT AND co_periodo.I_ParametroID = 5
WHERE	NOT EXISTS (
			SELECT TP_CD2.I_ProcesoID , COUNT(TP_CD2.I_ProcesoID)
			  FROM TEMP_PROC TP_CD2
				   LEFT JOIN (SELECT DISTINCT cuota_pago, ano, p FROM temporal_pagos..cp_pri WHERE eliminado = 0) TP_CP ON TP_CP.cuota_pago = TP_CD2.I_ProcesoID
			 WHERE TP_CD2.I_ProcesoID = TEMP.I_ProcesoID
			GROUP BY TP_CD2.I_ProcesoID
			HAVING COUNT(TP_CD2.I_ProcesoID) > 1
		)
UNION
SELECT	I_ProcesoID, I_CatPagoID, T_ProcesoDesc, I_Anio, NULL AS I_Periodo, N_CodBanco, D_FecVencto, I_Prioridad, B_Mora, 
		B_Migrado, TEMP.B_Habilitado, TEMP.B_Eliminado
FROM	TEMP_PROC TEMP
WHERE	EXISTS (
			SELECT TP_CD2.I_ProcesoID , COUNT(TP_CD2.I_ProcesoID)
			  FROM TEMP_PROC TP_CD2
				   LEFT JOIN (SELECT DISTINCT cuota_pago, ano, p FROM temporal_pagos..cp_pri WHERE eliminado = 0) TP_CP ON TP_CP.cuota_pago = TP_CD2.I_ProcesoID
			 WHERE TP_CD2.I_ProcesoID = TEMP.I_ProcesoID
			GROUP BY TP_CD2.I_ProcesoID
			HAVING COUNT(TP_CD2.I_ProcesoID) > 1
		)
UNION
SELECT CAST(TP_CD.CUOTA_PAGO AS INT) CUOTA_PAGO, I_CatPagoID, TP_CD.DESCRIPCIO, 
	   CASE ISNUMERIC(LTRIM(SUBSTRING(LTRIM(TP_CD.DESCRIPCIO),1,4))) WHEN 1 THEN SUBSTRING(LTRIM(TP_CD.DESCRIPCIO),1,4) ELSE NULL END AS I_Anio, 
	    NULL AS I_Periodo, CODIGO_BNC, FCH_VENC, PRIORIDAD, CASE C_MORA WHEN 'VERDADERO' THEN 1 WHEN 'FALSO' THEN 0 ELSE NULL END AS C_MORA,
		1 AS B_Migrado, 1 AS B_Habilitado, TP_CD.ELIMINADO
FROM TC_CategoriaPago CP  
	  INNER JOIN temporal_pagos..cp_des TP_CD ON TP_CD.CODIGO_BNC IS NULL AND CP.B_Obligacion = 0 
WHERE TP_CD.ELIMINADO = 0





SELECT CAST(TP_CD.CUOTA_PAGO AS INT) CUOTA_PAGO, I_CatPagoID, TP_CD.DESCRIPCIO, 
	   CASE ISNUMERIC(LTRIM(SUBSTRING(LTRIM(TP_CD.DESCRIPCIO),1,4))) WHEN 1 THEN SUBSTRING(LTRIM(TP_CD.DESCRIPCIO),1,4) ELSE NULL END AS I_Anio, 
	    NULL AS I_Periodo, CODIGO_BNC, FCH_VENC, PRIORIDAD, CASE C_MORA WHEN 'VERDADERO' THEN 1 WHEN 'FALSO' THEN 0 ELSE NULL END AS C_MORA,
		1 AS B_Migrado, 1 AS B_Habilitado, TP_CD.ELIMINADO
FROM TC_CategoriaPago CP  
	  INNER JOIN temporal_pagos..cp_des TP_CD ON TP_CD.CODIGO_BNC IS NULL AND CP.B_Obligacion = 0 
WHERE TP_CD.ELIMINADO = 0
	  AND NOT EXISTS (
			  SELECT TP_CD2.CUOTA_PAGO , COUNT(TP_CD2.CUOTA_PAGO)
				FROM TC_CategoriaPago CP  
					  INNER JOIN temporal_pagos..cp_des TP_CD2 ON CP.N_CodBanco COLLATE DATABASE_DEFAULT = TP_CD2.CODIGO_BNC COLLATE DATABASE_DEFAULT
					  LEFT JOIN (SELECT DISTINCT cuota_pago, ano, p FROM temporal_pagos..cp_pri WHERE eliminado = 0) TP_CP ON TP_CP.cuota_pago = TP_CD2.CUOTA_PAGO
				WHERE TP_CD2.CUOTA_PAGO = TP_CD.CUOTA_PAGO AND TP_CD2.ELIMINADO = 0 AND CODIGO_BNC IN (
						'0635','0636','0638','0670','0671','0674',
						'0675','0678','0679','0680','0681','0682',
						'0683','0689','0690','0691','0692','0695',
						'0696','0697','0698'
						)
				GROUP BY TP_CD2.CUOTA_PAGO
				HAVING COUNT(TP_CD2.CUOTA_PAGO) > 1
	  )
UNION
SELECT CAST(TP_CD.CUOTA_PAGO AS INT) CUOTA_PAGO, I_CatPagoID, TP_CD.DESCRIPCIO, 
	   CASE ISNUMERIC(LTRIM(SUBSTRING(LTRIM(TP_CD.DESCRIPCIO),1,4))) WHEN 1 THEN SUBSTRING(LTRIM(TP_CD.DESCRIPCIO),1,4) ELSE NULL END AS I_Anio, 
	   NULL AS I_Periodo, CODIGO_BNC, FCH_VENC, PRIORIDAD, CASE C_MORA WHEN 'VERDADERO' THEN 1 WHEN 'FALSO' THEN 0 ELSE NULL END  AS C_MORA,
	   1 AS B_Migrado, 1 AS B_Habilitado, TP_CD.ELIMINADO
FROM TC_CategoriaPago CP  
	  INNER JOIN temporal_pagos..cp_des TP_CD ON CP.N_CodBanco COLLATE DATABASE_DEFAULT = TP_CD.CODIGO_BNC COLLATE DATABASE_DEFAULT
WHERE TP_CD.ELIMINADO = 0 AND CODIGO_BNC IN (
		'0635','0636','0638','0670','0671','0674',
		'0675','0678','0679','0680','0681','0682',
		'0683','0689','0690','0691','0692','0695',
		'0696','0697','0698'
		)
	  AND EXISTS (
			SELECT TP_CD2.CUOTA_PAGO , COUNT(TP_CD2.CUOTA_PAGO)
			FROM TC_CategoriaPago CP  
					INNER JOIN temporal_pagos..cp_des TP_CD2 ON CP.N_CodBanco COLLATE DATABASE_DEFAULT = TP_CD2.CODIGO_BNC COLLATE DATABASE_DEFAULT
					LEFT JOIN (SELECT DISTINCT cuota_pago, ano, p FROM temporal_pagos..cp_pri WHERE eliminado = 0) TP_CP ON TP_CP.cuota_pago = TP_CD2.CUOTA_PAGO
			WHERE TP_CD2.CUOTA_PAGO = TP_CD.CUOTA_PAGO AND TP_CD2.ELIMINADO = 0 AND CODIGO_BNC IN (
					'0635','0636','0638','0670','0671','0674',
					'0675','0678','0679','0680','0681','0682',
					'0683','0689','0690','0691','0692','0695',
					'0696','0697','0698'
					)
			GROUP BY TP_CD2.CUOTA_PAGO
			HAVING COUNT(TP_CD2.CUOTA_PAGO) > 1
	  )



